### ISSUE TITLE
Certificate Issue - Invalid Certificate for Domain

### ISSUE THREAD

**Issue by Khaled0P** [adoringdo/BMWelektronika#11]
**Description:**
We are encountering a certificate issue when accessing the site through a browser. The error message indicates that the SSL certificate used is not valid for the domain.

**Steps to Reproduce:**
1. Open a web browser.
2. Navigate to our website using the linked domain.
3. Observe the certificate error.

**Expected Behavior:**
The website should be accessible without any certificate errors, and the certificate should be valid for the linked domain.

**Actual Behavior:**
The browser displays an error indicating that the certificate is not valid for the domain.

**Additional Information:**
- Domain: [https://bmwelektronika.tech/](https://bmwelektronika.tech/)
- Certificate Error Message: this site uses a certificate that is not valid for bmwelektronika.tech. The certificate is only valid for the following names: *.github.io, github.io, *.github.com, github.com, www.github.com, *.githubusercontent.com, githubusercontent.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Possible Solution:**
- Verify that the SSL certificate is correctly installed on the server.
- Check the certificate expiration date to ensure it has not expired.
- Ensure that the common name (CN) or subject alternative names (SANs) on the certificate match the domain.
- Confirm that the certificate chain is complete and correctly configured.
- Review the web server configuration to make sure it is set up to use the correct SSL certificate.
- Since we're using a third-party SSL certificate provider, ensure that the certificate is issued for the correct domain.
- Check for any recent changes in the server environment that might have affected the SSL configuration.

**Priority:**
High

**Comment by Khaled0P** [comment]
@adoringdo I'll leave this one to you since the SSL certificate provider website is in Lithuanian. Feel free to let me know if you need any help or if you get stuck.

**Comment by adoringdo** [comment]
Issue solved.

Resolution Steps:
To address the issue, the following steps were taken:

DNS Settings:
Removed all existing A records.
Added new A records pointing to GitHub IP addresses.

Web Server Configuration:
Edited the .htaccess file in the domain file manager to enforce HTTPS redirection.

Result:
Following the adjustment of DNS settings and the configuration of the web server, the SSL certificate issue was successfully resolved. The website is now accessible without any certificate errors, and the certificate is valid for the linked domain.
